//------------CUSTOMERS API ------------//

###
GET http://localhost:3000/customers
###
GET http://localhost:3000/customers/29d85c85-0073-4810-9396-4feb6a5b4dda
###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 22"
}

###
PATCH http://localhost:3000/customers/2eb0a132-37aa-4abd-adcd-e2dac77ec71c
Content-Type: application/json

{
    "name": "name updated"
}

###
DELETE http://localhost:3000/customers/5e6903d1-6dd5-4508-86ed-2c15b6725ce0


//------------CAMERAS API ------------//

###
GET http://localhost:3000/cameras?isEnabled=false

//Find cameras by customer id
###
GET http://localhost:3000/cameras/findCamerasByCustomer/885f34bc-c07f-43e6-af1b-40c8ed7b9350
###

GET http://localhost:3000/cameras/29d85c85-0073-4810-9396-4feb6a5b4dda
###
POST http://localhost:3000/cameras
Content-Type: application/json

{
    "name": "Camera 222",
    "ip": "226.81.216.233",
    "isEnabled": true,
    "customerId": "702464fa-c613-4fea-8591-bdb3d300e342"
}

###
PATCH http://localhost:3000/cameras/29d85c85-0073-4810-9396-4feb6a5b4dda
Content-Type: application/json

{
    "isEnabled": false
}

###
DELETE http://localhost:3000/cameras/9eb2664d-70c2-4625-a36b-b554ae51fc61
###
PATCH http://localhost:3000/cameras/activateCamera/48884eab-04bf-49ca-8c04-7027b86a6046
Content-Type: application/json

###
PATCH http://localhost:3000/cameras/deactivateCamera/665f6459-9dcf-4135-8d06-443cc9c2e0b9
Content-Type: application/json



//------------ALERTS API ------------//

###
GET http://localhost:3000/alerts?customerId=885f34bc-c07f-43e6-af1b-40c8ed7b9350&cameraId=74ea54ff-881b-4dab-935e-02f4d8b879b4&startDate=2021-02-21&endDate=2023-03-01
###
GET http://localhost:3000/alerts/29d85c85-0073-4810-9396-4feb6a5b4dda
###


//Find alerts by date interval
###
POST  http://localhost:3000/alerts/findAlertsByDateInterval
Content-Type: application/json

{
    "startDate": "2021-02-21",
    "endDate": "2023-03-01"
}

###

//Register an alert
POST http://localhost:3000/alerts
Content-Type: application/json

{
    "occurredAt": "2023-10-25T00:00:00.000Z",
    "cameraId": "74ea54ff-881b-4dab-935e-02f4d8b879b4"
}

###
PATCH http://localhost:3000/alerts/ba8c5754-b4dc-467c-a7e8-795c809316e5
Content-Type: application/json

{
    "occurredAt": "2022-02-01T03:44:33.060Z"
}

###
DELETE http://localhost:3000/alerts/ba8c5754-b4dc-467c-a7e8-795c809316e5
