GET http://localhost:3000/cameras
###
GET http://localhost:3000/cameras/29d85c85-0073-4810-9396-4feb6a5b4dda
###
POST http://localhost:3000/cameras
Content-Type: application/json

{
    "name": "Camera 15",
    "ip": "226.81.216.235",
    "isEnabled": true,
    "customerId": "2eb0a132-37aa-4abd-adcd-e2dac77ec71c"
}

###
PATCH http://localhost:3000/cameras/29d85c85-0073-4810-9396-4feb6a5b4dda
Content-Type: application/json

{
    "isEnabled": false
}

###
DELETE http://localhost:3000/cameras/9eb2664d-70c2-4625-a36b-b554ae51fc61
###
PATCH http://localhost:3000/cameras/activateCamera/48884eab-04bf-49ca-8c04-7027b86a6046
Content-Type: application/json

###
PATCH http://localhost:3000/cameras/deactivateCamera/48884eab-04bf-49ca-8c04-7027b86a6046
Content-Type: application/json


//CUSTOMERS API

###
GET http://localhost:3000/customers
###
GET http://localhost:3000/customers/29d85c85-0073-4810-9396-4feb6a5b4dda
###
POST http://localhost:3000/customers
Content-Type: application/json

{
    "name": "Customer 1"
}

###
PATCH http://localhost:3000/customers/2eb0a132-37aa-4abd-adcd-e2dac77ec71c
Content-Type: application/json

{
    "name": "name updated"
}

###
DELETE http://localhost:3000/customers/5e6903d1-6dd5-4508-86ed-2c15b6725ce0